version: '3.8'
services:
  database:
    container_name: postgres
    image: postgres:alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=localpass
      - POSTGRES_DB=to_do
    ports:
      - '5001:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:


